### ISSUE TITLE
/admin/products/list and /marketplace/list not loading

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#326]
The pages /admin/products/list and /marketplace/list are not loading.  I put these together as I suspect it is the same issue.

Error message:
````
Failed to load resource: the server responded with a status of 422 (Bad Request)
````

**Comment by stackus** [comment]
This appears to have been resolved with the cloud fixes from earlier this week.

**Comment by chriskacerguis** [comment]
I still can't add products here

http://jellyfish-ux-dev.dpi.bah.com/admin/products/list

**Comment by stackus** [comment]
I recognize this 'situation'. The seed data failed to completely load. It got as far as loading users but then it failed while trying to load products. Since products are loaded for before product types we're not seeing any of those.

The solution is to clear out the DB and then re-seed.

**Comment by chriskacerguis** [comment]
That should be done on every build.  Let me check

**Comment by chriskacerguis** [comment]
@stackus did a rebuild.  No products.  I don't even have an add products button
